import type { CreateConfigValues } from "@rudderhq/agent-runtime-utils";
import { AGENT_RUN_CONCURRENCY_DEFAULT } from "@rudderhq/shared";

export const defaultCreateValues: CreateConfigValues = {
  agentRuntimeType: "claude_local",
  cwd: "",
  instructionsFilePath: "",
  promptTemplate: "",
  model: "",
  thinkingEffort: "",
  chrome: false,
  dangerouslySkipPermissions: true,
  search: false,
  dangerouslyBypassSandbox: false,
  command: "",
  args: "",
  extraArgs: "",
  envVars: "",
  envBindings: {},
  url: "",
  bootstrapPrompt: "",
  payloadTemplateJson: "",
  workspaceStrategyType: "project_primary",
  workspaceBaseRef: "",
  workspaceBranchTemplate: "",
  worktreeParentDir: "",
  runtimeServicesJson: "",
  maxTurnsPerRun: 300,
  heartbeatEnabled: false,
  intervalSec: 300,
  maxConcurrentRuns: AGENT_RUN_CONCURRENCY_DEFAULT,
};
